language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
before_script:
- npm install -g hexo
- npm install -g firebase-tools
- npm install
script:
- hexo generate
after_success:
- firebase deploy -m "build id:$TRAVIS_BUILD_ID, build number:$TRAVIS_BUILD_NUMBER" --token $FIREBASE_TOKEN --non-interactive