language: node_js
node_js:
- node
branches:
  only:
  - master
cache:
  directories:
  - node_modules
install:
- npm install -g hexo
before_deploy:
- npm install
- hexo generate
deploy:
  provider: firebase
  token:
    secure: L5yxAym48bpuVK62NB/txmmTPeG97GX/MclBzULkROtr6LuECWh00Zc1SQoFJl5PoCxHsoEKqG4+J5BE3bN6ftE9SHlaXXxjlkJE21vUVULICrSPviGUdrpemLjD2JV2NRehPVHEuNWWnIgIyCtwZJLZwCxpa2DD2u3JeTLOJvq0THQrBThq8es4/0ekNHAA3O5Zr9pJ2/Ja4deAmndEf+y4n3icwX959Qh3LWv18snrs9FOGKybuHplTDafMqRprnbf1b2khyqM31b/rf9WFGl6KWpIhqa0i/siY98U+zGYL24tWHat6a6ql19I3PTKDqCwiVuXJMk0cAh3QoglDN9WUGgRw1oDcK0/vWK3pEh1DtxFvGkuE09aiQVf0noJoV5T1cw52Uqjl2OdI8yrsVFzcrWfvOO2Fl219C5SidM0B680D4le75X9LPn4jkleOmOXRS1DWbK/1jtTN0lJAvbKSW2VJdvqAkR7hNu6v03hb5f4KS0UIAr8EVbOdqUBnN8u9884Mo/8nAZm7VHxHyul8zTBorIyA3awC7aukBxdCysQTFTVB/Gp4LfcQ/gRU8+yrNk0RJhgeeQlcR4Q26TQrHXsAusAkRIahdd/PtG4jz/VJgKtvo4nh8S6QX8tnhiTOiJImCX8nVUbhl/9qMKBdtWcQpi9N0zwcwMdJCM=
